# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################


from module_info import *
sf_day        = 0x00000000
sf_dawn       = 0x00000001
sf_night      = 0x00000002

sf_clouds_0   = 0x00000000
sf_clouds_1   = 0x00000010
sf_clouds_2   = 0x00000020
sf_clouds_3   = 0x00000030

sf_no_shadows = 0x10000000
sf_HDR        = 0x20000000  # this will generate HDR-shaded skyboxes, you should make a LDR version of your skybox for compatibility

# mesh_name, flags, sun_heading, sun_altitude, flare_strength, postfx, sun_color, hemi_color, ambient_color, (fog_start, fog_color),

# to generate new skybox textures with hdr option:
# hdr images are required to generate our RGBE coded skybox images


# To add a skybox, you should first edit this file and put new skyboxes.txt file into the "Data/" folder of your module. 
# The first "mesh_name" parameter is the name of the skybox mesh to be used for that entry. 
# You can check our meshes from the "skyboxes.brf" file with OpenBRF and copy them, 
# just replace the material's textures with yours. And you will also have to change the 
# specular color parameters for correct hdr rendering. of course specular color does not 
# corresponds to specular lighting, those parameters are used as compression values 
# for RGBE decoding and should be generated while you generate RGBE textures. 
# (specular.red = Scale component, specular.green = Bias component) 
# You can check our materials for the instances of this usage. 
#
# For skybox textures, we are using uncompressed *.hdr files to generate *_rgb.dds and *_exp.dds files. 
# its just a RGBE encoding of the skybox for hdr lighting. here is an example: 
# "skybox.dds" -> simple non-hdr (LDR) image, used when you dont use hdr (DXT1 format is good)
# "skybox_rgb.dds" -> RGB components of the HDR image (DXT1 format is preffered)
# "skybox_exp.dds" -> E (exponent) component of the HDR image (L16 format is good, you can use half resolution for this texture)
# We are using our own command line tool to generete those files from "skybox.hdr" image. 
# But you can generate them with some of the hdr-image editors too. The images should be gamma corrected and should not have mipmaps. 
# You can use Photoshop with DDS plug-ins or DirectX Texture Viewer to see the contents of our dds images. 
# 
# ..visit Taleworlds Forums for more information..

skyboxes = [
  ("skybox_clearday", sf_day|sf_clouds_1, 179, 52, 0.9, "pfx_sunny", (1.8348, 1.6819, 1.5012), (0, 0, 0), (0.060235, 0.088471, 0.167529), (300, 0xFF8CA2AD)),
  ("skybox_cloud_13", sf_day|sf_clouds_1|sf_HDR, 179, 52, 0.91, "pfx_sunny", (1.8348, 1.6819, 1.5012), (0, 0, 0), (0.053961, 0.079255, 0.150078), (300, 0xFF8CA2AD)),
  ("skybox_cloud_03", sf_day|sf_clouds_1|sf_HDR, 179, 52, 0.91, "pfx_sunny", (1.8348, 1.6819, 1.5012), (0, 0, 0), (0.053961, 0.079255, 0.150078), (300, 0xFF8CA2AD)),
  ("skybox_cloud_16", sf_day|sf_clouds_1|sf_HDR, 179, 52, 0.91, "pfx_sunny", (1.8348, 1.6819, 1.5012), (0, 0, 0), (0.053961, 0.079255, 0.150078), (300, 0xFF8CA2AD)),
  ("skybox_night_2", sf_night|sf_clouds_3, 152, 38, 0, "pfx_night", (0.066667, 0.082353, 0.105882), (0, 0, 0), (0.017647, 0.017647, 0.052941), (500, 0xFF152035)),
  ("skybox_night_2", sf_night|sf_clouds_3|sf_HDR, 152, 38, 0, "pfx_night", (0.066667, 0.082353, 0.105882), (0, 0, 0), (0.017647, 0.017647, 0.052941), (500, 0xFF152035)),
  ("skybox_night_1", sf_night|sf_clouds_1, 152, 38, 0, "pfx_night", (0.066667, 0.082353, 0.105882), (0, 0, 0), (0.017647, 0.017647, 0.052941), (500, 0xFF152035)),
  ("skybox_night_1", sf_night|sf_clouds_1|sf_HDR, 152, 38, 0, "pfx_night", (0.066667, 0.082353, 0.105882), (0, 0, 0), (0.017647, 0.017647, 0.052941), (500, 0xFF152035)),
  ("skybox_night_03", sf_night|sf_clouds_1, 152, 38, 0, "pfx_night", (0.066667, 0.082353, 0.105882), (0, 0, 0), (0.017647, 0.017647, 0.052941), (500, 0xFF152035)),
  ("skybox_night_03", sf_night|sf_clouds_1|sf_HDR, 152, 38, 0, "pfx_night", (0.066667, 0.082353, 0.105882), (0, 0, 0), (0.017647, 0.017647, 0.052941), (500, 0xFF152035)),
  ("skybox_sunset_1", sf_dawn|sf_clouds_1, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_02", sf_dawn|sf_clouds_1|sf_HDR, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_03", sf_dawn|sf_clouds_1, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_04", sf_dawn|sf_clouds_1|sf_HDR, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_05", sf_dawn|sf_clouds_1, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_06", sf_dawn|sf_clouds_1|sf_HDR, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_07", sf_dawn|sf_clouds_1|sf_HDR, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_08", sf_dawn|sf_clouds_1|sf_HDR, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_sunset_09", sf_dawn|sf_clouds_1|sf_HDR, 180, 9.146, 0.7, "pfx_sunset", (1.045455, 0.545455, 0.168182), (0, 0, 0), (0.069048, 0.1, 0.190476), (150, 0xFF897262)),
  ("skybox_cloud_08", sf_day|sf_clouds_2, 180, 19.17, 0.4, "pfx_cloudy", (0.72, 0.68, 0.6), (0, 0, 0), (0.12549, 0.145882, 0.241569), (120, 0xFF607090)),
  ("skybox_cloud_2", sf_day|sf_clouds_2|sf_HDR, 180, 19.17, 0.4, "pfx_cloudy", (0.72, 0.68, 0.6), (0, 0, 0), (0.12549, 0.145882, 0.241569), (120, 0xFF607090)),
  ("skybox_cloud_09", sf_day|sf_clouds_2, 180, 19.17, 0.4, "pfx_cloudy", (0.72, 0.68, 0.6), (0, 0, 0), (0.12549, 0.145882, 0.241569), (120, 0xFF607090)),
  ("skybox_cloud_1", sf_day|sf_clouds_2|sf_HDR, 180, 19.17, 0.4, "pfx_cloudy", (0.72, 0.68, 0.6), (0, 0, 0), (0.12549, 0.145882, 0.241569), (120, 0xFF607090)),
  ("skybox_cloud_06", sf_day|sf_clouds_2, 180, 19.17, 0.4, "pfx_cloudy", (0.72, 0.68, 0.6), (0, 0, 0), (0.12549, 0.145882, 0.241569), (120, 0xFF607090)),
  ("skybox_cloud_15", sf_day|sf_clouds_2|sf_HDR, 180, 19.17, 0.4, "pfx_cloudy", (0.72, 0.68, 0.6), (0, 0, 0), (0.12549, 0.145882, 0.241569), (120, 0xFF607090)),
  ("skybox_cloud_04", sf_day|sf_clouds_3|sf_no_shadows, 180, 19.17, 0.36, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_cloud_05", sf_day|sf_clouds_3|sf_no_shadows|sf_HDR, 180, 19.17, 0.38, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_cloud_07", sf_day|sf_clouds_3|sf_no_shadows, 180, 19.17, 0.39, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_cloud_10", sf_day|sf_clouds_3|sf_no_shadows|sf_HDR, 180, 19.17, 0.33, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_cloud_11", sf_day|sf_clouds_3|sf_no_shadows, 180, 19.17, 0.4, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_cloud_12", sf_day|sf_clouds_3|sf_no_shadows|sf_HDR, 180, 19.17, 0.39, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_cloud_14", sf_day|sf_clouds_3|sf_no_shadows, 180, 19.17, 0.4, "pfx_overcast", (0.4, 0.35, 0.31), (0, 0, 0), (0.196078, 0.235294, 0.403922), (120, 0xFF607090)),
  ("skybox_clear_02", sf_day|sf_clouds_0, 179, 80, 1.05, "pfx_sunny", (1.3068, 1.1979, 1.0692), (0, 0, 0), (0.060235, 0.088471, 0.167529), (300, 0xFF8CA2AD)),
  ("skybox_clear_02", sf_day|sf_clouds_0|sf_HDR, 179, 80, 1.1, "pfx_sunny", (1.3068, 1.1979, 1.0692), (0, 0, 0), (0.053961, 0.079255, 0.150078), (300, 0xFF8CA2AD)),
]
def save_skyboxes():
  file = open(export_dir + "Data/skyboxes.txt","w")
  file.write("d\n"%len(skyboxes))
  for skybox in  skyboxes:
    file.write("%s %d %f %f %f %s\n"%(skybox[0],skybox[1],skybox[2],skybox[3],skybox[4],skybox[5]))
    file.write(" %f %f %f "%skybox[6])
    file.write(" %f %f %f "%skybox[7])
    file.write(" %f %f %f "%skybox[8])
    file.write(" %f %d\n"%skybox[9])
  file.close()

print "Exporting skyboxes..."
save_skyboxes()